-- Disciplina: Banco de Dados Avançado - Professor Gilmar Borba
-- Atividade 02: Banco CLIENTES_E_PEDIDOS
-- Insere Unidades
insert into Unidade (sigla, descricao) values ('Unid', 'Unidade')
insert into Unidade (sigla, descricao) values ('Peça', 'Peça/Unidade')
insert into Unidade (sigla, descricao) values ('Litro', 'Litro')
insert into Unidade (sigla, descricao) values ('Saco', 'Saco com 25 kg')
insert into Unidade (sigla, descricao) values ('Kg', 'Kilograma')
insert into Unidade (sigla, descricao) values ('M3', 'Metro cúbico')
insert into Unidade (sigla, descricao) values ('M2', 'Metro quadrado')
insert into Unidade (sigla, descricao) values ('MLin', 'Metro linear')
insert into Unidade (sigla, descricao) values ('Ml', 'Mililitro')
insert into Unidade (sigla, descricao) values ('Ton', 'Tonelada')
insert into Unidade (sigla, descricao) values ('Grao', 'Grão')
insert into Unidade (sigla, descricao) values ('Sem', 'Semente')
insert into Unidade (sigla, descricao) values ('Folha', 'Folha')
insert into Unidade (sigla, descricao) values ('Pct1k', 'Pacote com 1 kilograma')
insert into Unidade (sigla, descricao) values ('Pct2k', 'Pacote com 2 kilogramas')