-- Disciplina: Banco de Dados Avançado - Professor Gilmar Borba
-- Atividade 02: Banco CLIENTES_E_PEDIDOS
-- Insere Conferentes - ok!
insert into Conferente (nome, contato) values ('Alessanderson Diorégenes', '31-9988-7766')
insert into Conferente (nome, contato) values ('Arquiteclínio Ramátis', '31-1188-1166')
insert into Conferente (nome, contato) values ('Petrocoquínio Durvadilandi', '31-1188-1166')
insert into Conferente (nome, contato) values ('Benemérita Maracajá', '31-1122-1122')
insert into Conferente (nome, contato) values ('Hericlapiton da Silva', '31-1144-2222')
insert into Conferente (nome, contato) values ('Marili Monrói', '31-4552-6622')
insert into Conferente (nome, contato) values ('Irisdelfane Clei', '31-9922-1122')
insert into Conferente (nome, contato) values ('Lindulfo Colodônio', '31-1882-1122')
insert into Conferente (nome, contato) values ('Ivandilson Patolino', '31-1122-8877')
GO